### ISSUE TITLE
Please review and provide feedback

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/ruby-data-structures-algorithms-two-sum#1]
This is a first take at writing a data structures and algorithms module assignment. Any @DPI-WE/teaching-assistants have time to give it a shot and provide feedback?

**Comment by thierrychau** [comment]
- Suggestion for overall structure / breaking it down in paragraphs. I'm thinking that we want trainees to follow a thought pattern (`Acing the code interview` https://github.com/DPI-WE/ruby-data-structures-algorithms-intro/issues/1#issuecomment-1968225558)
  - The problem
  - Understand the Problem
  - (Think Aloud?)
  - Code repl  (or "Test your code")
  - Tips and Clues for Solving the problem
  - Knowledge Quiz
- Thoughts on moving the code repl before `Tips and Clues`? I think trying first without having the answer helps a lot with information retention. Framing the module to give this opportunity could be beneficial.

**Comment by heratyian** [comment]
Love this. ++ great feeback

**Comment by heratyian** [comment]
re-strucutured the lesson in this commit ec2a1c231bdd7f1e0028edb5e68279b58aa6b287
